#!/ffp/bin/sh
set -x

export PATH=/usr/sbin:/usr/bin:/sbin:/bin:/ffp/sbin:/ffp/bin
umask 022

mount -t proc proc /proc

# Now, search partitions for /linux/sbin/init, then chroot to linux
# and exec sbin/init.

for d in $(fdisk -l | grep 'Linux$' | cut -d' ' -f1); do
	mount $d /mnt || continue
	if [ -x /mnt/linux/sbin/init ]; then
		cd /mnt/linux
		exec chroot . /sbin/init
	fi
	umount /mnt
done

# nothing found
exec /bin/sh

